// <auto-generated />
using System;
using MentorShip.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MentorShip.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210201160254_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MentorShip.Models.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<string>("Departmant");

                    b.Property<string>("Email");

                    b.Property<string>("Job");

                    b.Property<string>("Parola");

                    b.Property<string>("Soyad");

                    b.HasKey("Id");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("MentorShip.Models.Resume", b =>
                {
                    b.Property<int?>("Id");

                    b.Property<string>("Address");

                    b.Property<string>("Deneyim");

                    b.Property<DateTime>("Dob");

                    b.Property<string>("ForeignLanguage");

                    b.Property<string>("HighSchool");

                    b.Property<string>("Hobies");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Skills");

                    b.Property<string>("University");

                    b.HasKey("Id");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("MentorShip.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<string>("Departmant");

                    b.Property<string>("Email");

                    b.Property<string>("Parola");

                    b.Property<string>("Soyad");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MentorShip.Models.Resume", b =>
                {
                    b.HasOne("MentorShip.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
